sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: cXCpZIGvAOvqbtdn4cobMO476QOMqhXKSJi3K0ogUQXd3fahTVU2TsPaTy5vOnlFt/lUdM263NJq2PWWDssBX2alSD7qTpvWohNMv0Xj772nr1AMtzETfOg2a1Nj678CExZLK/X+1kX6s8jkO03Np6ub7R9jve34L4CsoRPCwhS+ZTSnDagUuWys7dVf7C5Zs8tMvn6vrtvEggAFzlVBE9/hGrmuMlNr1aYQ8//mUch1J5K0pD1XQCq8KRqzWChgX+P6t8Jw8oe7ZyiAdACAQ4DpqE8+1E4X2BmgdLpjnjG5iRj7OvXz1+SNV6Vqml9khf7u8wOZSVn2IUq9CGnKlKDhUOo+Dw6ZE38IAwkwfLqJlZUzmYmtraCTELEs9hdrfPOUecvbx0fRGilndnutbwEGYv6h5ZLB79xBU9THmcfZswszo7VkAIz6lceoNXAPCYipthv7tmDjs3bweQai/bZMXeCU9Zuv3SNmOV+zL677zdjmzoaUoiSvUURmaBw0u72UXHUpwRrqEbDxn3pd67fpD2MhUBbFtJImzvelqlHohAqO89wmgCOs8b7ipd3VSGbthpM//UtFbbhjIfLH0O8njh2jqaCQUEqTZBFjSaqwKKMiRWWs1E3svxAysEjOez55tN7W4bzDEHrCp4m6/x2Rl2bCzU83G1ZbU0MErSk=
  - secure: B2ZWLlFt7W8WO/z5TRMjGtZQXD7+J3qLMgF+mzEjHE/OFfGEnR/VxMnMfSBbh3zWFW4eTQuHnrhWYARd2xMlvk6OMKPrunSohGCvSxLjKDUCLOrMKONRARBbkq0i8cMkyGmT2+UgAlhlcWgwqUZTZISWmU+ChVca+OLfw2xmTbo6AVWzKykKiOJqyyUJcvOvudwptN7oEvmw56vBAMxug70OQd+A0gR9y0XsXXSk/IFYdu983JM/M5cszFvALpC6kNTSyxfreR51uaFuzxXS0v22v2WQFBICVeFa03brR8lShNG0jnywLiazSOHcz6PEwZRYYobL+dIqvBIsWz2CrcHME/n4CCiNWnPW1ZPTUgCGWbz6BWO3t3qsPTy0CB6axkOlk1tc8kQjXz7mscC5Q+g4VYzDuBKiZa35xJEDL1BUc/W5ORBu/iNW8ALkpmkbGrM1mAQJLXiPnR9mFGCwOdpBo3vTVb3n10Yme52AmSGNAnCShns3oLa8LORFiVIFEOPhUGk/ujQF48MBx9v6vw4NUmBwgxyRvTUbYcFJS2z36YAmM7Z4NjzThEGAL7g+eNI4Nu9LiE9QpHpaYD3LsIqjExW/jvi/8kWpCKOofpYxx7H+c2Kh20A7Jav86dhstpDg6+r6Oplxh4Jfarnb/mpysx646MpBw+aG3USnHcI=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
