sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Qw9wqihzA4fnMSdIWSTmKaaookzEqzbRqbkPLQD0GGjvwLidgKUvXK6w+KlRZi24uXZphMKnrAyRX5BpvBJZlpif1ItzS/tKLWu2+s5b7NuvvE2TvU8ATlCMA7WBCssOUSAzLTMEFcwSvDLZLgyo6nYqiaYCDuSBqg5oHmYCx21CYd08czql3tnwS/2y71c2FSY7IU3cayWYeWGJR+wOGhTZoERgOhWPbaCzF8a/rHGLc9GXfEpTmD10ZZPwE+oy/C2M09IQnLXNSoErzWqWewV8ljWcht2JFuKIjd1mT4ztK/a7v9kShdfwIS+pF6lz102/b3CG4MIVgzSEq8cAgjPiV4XyONF41/G60qyjTNjaCJtmIsNcM9TVyuIADGK/QRQhOD7HXOhm1h/cdfgMtSd3HmOIyE2tZbNYcboHcbkv+oG7J2zK1zNqn+xChqGemyEy07isIxIehso1qJEcc03dXebqeyEXqnGB5zVT0V0bM5MxHX+1Z/7B9sLGfFwDyjRLhlENrJU/kl7xMfiBjTwi4rFo4/r8VcdUl2vNgRBTnbG3nB0lnDk50Wz8eR7mf8UIZrPxV7UAjvJUiw1o3/ls3X0HssX6VxkvJha2b6XUrBQzSMAH1AT7K/ldy8K67IMKZ7EZRtt9KMg+I2flMu75FQlr4L0oB6/8ZSgSVac=
  - secure: gKzMReDOAvbHsWOzvXI6f/4/lBWxLNtmyS4IdorOCdjwdNJ0O8r41qTuDp0PuHq/1IwWliMGRwf1wXZqQo/VkH/EgQJKeNI4X97CeeAk0RZPsfpvWb7PBYR5+w4HeQNn9xHim9nNSE1Hsr4BELA2TVfyfx90+T2cRMAOgKUjprsaTGRDMnWr1FL0sIRxgGv9qUIJR6QBofakAoIGFqiAxN3ymEn4kWzbZRglWvsm33oZPhWu1sZMh0DtAH6/oDRSQkBKPH1DeU043dmmwhz+hSRwvm4+AzZLPuHueFPI1Nyrc8nggwECmSE4RIA/warZ7frijf1rUWVRjjGuvNmDK+jrnmmU01bvVHdvKNvh570m8znV4EN29ReLcI16WmJnEwNXw95537lO6UdJtr5AJUMqJ5wTnC1LaJDBA+eODyVSrfy68JETFR9lpHAg/367trU+oqVsltf3l7mClSOBlMFrjcNFW3CdLELy4LuUKTaKC6ovOMgwFDmMwFzx0iEx7W9PPRKDZNV2GElKtiQo1ivaed9JfRsacndr+wCEpZlf3fBKRPJ2IUa10gwzsRhoZFECJm3vKbn18fYLws++ecjpelWDXITF3tzx4XvUgdsAg2I1xcfh20hrgbvL+QJ4DKcRrbaSTUW94weJEdA3R3fnXwFSlb39mSK8sbKxJzc=
  - secure: bQflmAlg3Imcqoy4LnYpR5b2MmilIUTfAMR51SIwTsLNo6o//Ue9qbgWSes6SlLzzlCW4LY72K96TrLX5kbt6THTxKRnzWvnV9sPAE5Fea1C1bENUqiVrZrBkVpBxbD7mmC+jEUWwlmxYhj0J8Elv+goETiNazr2BHvQUHIEB1mrm0q9RWHrvnBIosqqHvgNGXRkXZ0Z1V5xmmjPDVJiG6JK+n8chKZ7vUyja1DN70JUyj/GoGjYp8rMydeP3TEZ9GWJx2IdA6wtRQ1YCR1sXcIRKF0iuerw0wmKAFfzYaXfLCEFop2DfODwUmtEBa5WpR/wDj/FtBEC3ERUiiQX0xF5E2AKgBfhIiQv9Ijv9HCALJsgp8KfX2yNM82dudl0D2oewwR0O/OjkGiQ9iHOsb2LGDiXHdcqauq8B5saUk6pWqLFdVmXa+CbOO3lWAcIriCMmXhFUmcK9eKDKwUAnt2QoPEftTco/fV2es4gehvC2f9XOhM76A+dki7wGZMOsddWRv1bhse4cFE61t32ZSUys7T2Kdh6PedGhTmAun51hGAkbZudMA3KKnfYAkNRkYFHfNk+8f5lyOufdcGw0tL74GGBxBxgumeq7IdRWWW6KklA6IUkpk2a5BqKCfXt7jCAssJ/CM/oVs4033TFwTEBqOSUo+2pJdF5VSAtrYE=
